### ISSUE TITLE
Categories do not have a one-to-one corresponding mapping with OSM

### ISSUE THREAD

**Issue by angoca** [osmlab/onosm.org#126]
The list of categories is extensive, with many real options, but it has two issues.

* This is scary for a user who has not worked in OSM and could lead to dropping the form without creating a note.
* On the other side, when solving the notes generated from this site, it isn't easy to find the appropriate OSM tagging for each element. Therefore, this category does not provide a practical value and creates divergencies in mapping.

I have a fork where I changed the categories - https://maptimebogota.github.io/minegocio/#details. They could be better, but they are directly related to OSM map features - https://wiki.openstreetmap.org/wiki/Map_features, which are easier to map.

A smaller list of categories, including general categories, could be better when the user cannot identify the category.

**Comment by iandees** [comment]
The list of categories is there because it's better than free-form description, but I agree that a smaller list makes sense. I don't agree that it should be directly related to OSM map features, precisely because OSM doesn't have tagging for every type of business.

My desire would be to shorten the list of categories in the repo to make data suggestions easier.

**Comment by iandees** [comment]
Please feel free to open a PR to shorten the list.
