### ISSUE TITLE
Display existing notes

### ISSUE THREAD

**Issue by pyrog** [osmlab/onosm.org#55]
It's not possible to see If other users have already created notes in the aerea.

Could be fine to display notes created by onosm.org ?

**Comment by iandees** [comment]
The users submitting information shouldn't be bothered with existing notes, but I can see that it would be helpful for OSM mappers to see the notes that onosm.org created on an overview map or something.

**Comment by pyrog** [comment]
Are they really bothered if we display only notes created by onosm ?
They could see that somebody have "create" the same business before 😉

**Comment by stevevance** [comment]
I think the purpose is to get businesses, who likely know nothing about OSM, to submit their business. Showing any other information, like if their business has been submitted before, would be a distraction to that process. 

I don't think there's a concern that a business will be submitted more than once through this interface. An experienced OSM mapper will add it directly. The other competition for adding businesses via notes is the (wonderful) Maps.me app, but even if a business shows up 2x, one from each source (onosm and Maps.me), that's a problem I'd like to have because it probably means two people are interacting with OSM instead of one person. (And it could also mean that two people are providing different information, which could enhance the info we receive about that business.)

**Comment by alexandre-mbm** [comment]
It will is problematic if onosm become much known.

**Comment by ENT8R** [comment]
> but I can see that it would be helpful for OSM mappers to see the notes that onosm.org created on an overview map or something

I created a tool for that some time ago:

To show the last 100 notes created by onosm.org on a map:
https://ent8r.github.io/NotesReview/?query=onosm.org&limit=100&start=true

To show the last 100 notes created by onosm.org in a list:
https://ent8r.github.io/NotesReview/expert/?query=onosm.org&limit=100&start=true

I used my tool to resolve some notes created by this website and I never encountered notes which referenced the same business twice...

**Comment by hashtagdeamon** [comment]
When commenting on [issue 1929 of openstreetmap/openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/issues/1929) I encountered <= 24 open duplicates from onosm.org. 
Just as a reference the top 4 tuples:
- https://www.openstreetmap.org/note/1086346
- https://www.openstreetmap.org/note/1086343
- https://www.openstreetmap.org/note/1213146
- https://www.openstreetmap.org/note/1213149
- https://www.openstreetmap.org/note/932848
- https://www.openstreetmap.org/note/932847
- https://www.openstreetmap.org/note/1131366
- https://www.openstreetmap.org/note/1131367

Referring to the answer to the issue in the OSM repository, **onosm.org is responsible to avoid duplicates**.

**Comment by iandees** [comment]
I'm not going to display existing notes. That complicates the process.

The problem of "exact" duplicates is different. I disagree that it's the client's responsibility to avoid duplicates. If OSM cares enough about preventing duplicates, it should prevent duplicates on the server side. That being said, onosm can do some client-side work to try and prevent it: my guess is people are double-clicking the button in the final step. I can open a new ticket for that.
