### ISSUE TITLE
Please use OSM keys in the note text

### ISSUE THREAD

**Issue by GeorgV** [osmlab/onosm.org#64]
We found node with not standard OSM keys, which are used from onosm.org. My suggestion would be to use the OSM keys instead of the colloquial terms.
See https://github.com/osmlab/onosm.org/blob/gh-pages/js/site.js line 117-125
        "name: " + $("#name").val() + "\n" +
        "phone: " + $("#phone").val() + "\n" +
        "website: " + $("#website").val() + "\n" +
        "contact:twitter: " + $("#twitter").val() + "\n" +
        "opening_hours: " + $("#opening_hours").val() + "\n" +
        "shop/craft/office: " + $("#category").val() + "\n" +
        "addr:full: " + $("#address").val(),

**Comment by ENT8R** [comment]
Is this an accepted enhancement?

**Comment by iandees** [comment]
I purposefully made the note text use different key names to reinforce that the data should not be copied exactly from an onosm.org note. An OSM mapper should confirm that the place exists with a primary source and will likely need to fix formatting errors in the text from the submitter anyway, so I'm not interested in making this change.

See also #78

**Comment by eteb3** [comment]
This issue is the substance of my request [#78](https://github.com/osmlab/onosm.org/issues/78#event-3768440953).

I can see your aim as described above, but I don't personally see that the current output promotes a more careful check of the data as you intend.

Relieving mappers of cleaning up the format of the **_keys_** (and of replacing `: ` with `=`) just makes the mapper's life easier, making it more likely the notes will be incorporated into the map.

It's grunt-work, unrelated to any primary check of the substantive meaning of the **_values_**, or translating them from "everyday Joe" to "standard OSM".

**Comment by iandees** [comment]
What tool are you using where you can copy/paste the note text to create a new OSM object?

**Comment by eteb3** [comment]
Thanks for the response.

I use iD: I copy the note text and I paste into the 'tags' pane. (There are two options: tags separated, or tags as a single entry. I use the latter)

See [here](https://drive.google.com/file/d/1dF4gLLYZRpNLLBo1kWoybTGjFA1ljOgE/view?usp=sharing), if that's clear enough?

**Comment by xeruf** [comment]
I disagree with the sentiment. One can quickly check the website, glance at the data and then copy over everything, as eteb mentioned copying this by hand is useless grunt work.
If somebody wants to incorporate the data without checking, this won't stop them, and everyone else (i.e. most mappers) will just be annoyed.

**Comment by ahangarha** [comment]
As per my experience, the current implementation is just a torture for a mapper who is dedicating their time to convert notes into nodes.

There are easier ways to add trash data to the map.

This method, doesn't prevent "bad people" but discourages the good ones.
