### ISSUE TITLE
Make it easier to add data to the map

### ISSUE THREAD

**Issue by eteb3** [osmlab/onosm.org#78]
onosm.org notes can be useful (sometimes). 

But better formatting could make them much more useful, more of the time.

Example current output:

name: The Loaf Coffee & Sandwich Bar 
phone: 01234 5678910
website: 
twitter: undefined 
hours: 9am-5pm 
category: ,Cafés 
address: 12 Gloddaeth Street llandudno

This has to be manually translated into standard OSM tags:

All instances of `: `  must become `=`, and non-standard labels must be converted to standard tags (bold):

name=The Loaf Coffee & Sandwich Bar 
phone= **+44** 1234 5678910
website: 
twitter: undefined 
**opening_** hours = **Mo-Fr 09:00-17:00** 
category: ,Cafés 
**addr:housenumber=** 12
**addr:street=** Gloddaeth Street 
**addr:city=** llandudno

The extra keystrokes required mean I am likely not to act on these notes on my patch, and I fear they may become unresolved clutter.

**Comment by iandees** [comment]
This is a great idea, but the primary changes you're asking for here are:

* convert the opening hours from however the user enters them into the OSM opening_hours format
* convert the address from however the user enters it into the OSM tagging scheme

This would require some pretty large changes to be able to process the user-entered text, and the system would probably still get it wrong at least 50% of the time. I'd rather have a human enter/validate/correct this data in OSM based on what a person submitted. That's why the website creates notes instead of writing directly to OSM.
