### ISSUE TITLE
Opening hours syntax

### ISSUE THREAD

**Issue by angoca** [osmlab/onosm.org#93]
The opening hours should give example.

Or even better provide a way to correctly write them. A similar thing like a calendar to enter correct date, this option will allow to insert valid opening times.

**Comment by iandees** [comment]
The opening hours field is one of the primary reasons onosm.org still writes notes instead of writing directly to OSM. The website is designed to make it easier for people to submit data and leaves it up to the OSM mapper to translate that to valid OSM syntax.

I don't have plans to change that for now.
