### ISSUE TITLE
Additional information text box

### ISSUE THREAD

**Issue by OneKN1** [osmlab/onosm.org#98]
Just a text box for additional information.
We have masses of unclear notes. Sometimes some more information whould help out to unterstand what the other side is trying to tell us!
The character limitation of the text that is submittet should be about 200 chars.

**Comment by alex9099** [comment]
I agree, the current fields can be somewhat limiting, say the owner has instagram, some sort of more complex opening times (not sure about the limit on opening time), or some other things like description (in case the category isn't quite right or needs additional info)

**Comment by CurlingMan13** [comment]
What if the opening hours was formatter or had a similar input to what StreetComplete currently has?

**Comment by ArcaneDots** [comment]
I am not opposed the idea but you will have to keep in mind the barrier to entry that creates. We don't want to block a user from finishing a note because times are not in a form Open_hours' library can convert. There should be links to tutorials and such for those who are willing to try and a way to accept non-compliant input from who won't. Mappers will then have to use the conversion tool to parse it before adding the rest of the POI.  [Opening hours JS converter library](https://github.com/opening-hours/opening_hours.js) I would also create a separate issue for formal Open_Hours support.

**Comment by iandees** [comment]
I don't think I want to add any more free-form text. To get useful information from submitters, we need to direct them to give us useful information through prompts.

I see other specific requests for fields here, and those should be in separate tickets.
